Fix PRNGKeyArray.broadcast_to with scalar shape
jax-ml/jax pull request #10288
Opened 2022-04-14 20:09 UTC by YouJiacheng

2022-04-14 21:19 UTC, jakevdp requested changes
Looks good - add a test?

2022-04-14 21:27 UTC, YouJiacheng commented
Should I add a test directly use PRNGKeyArray? Or just test with PRNGKey(will not use PRNGKeyArray unless config set custom prng key, while CI doesn't set this.)

2022-04-14 21:29 UTC, jakevdp commented
I would probably add the test somewhere near here: https://github.com/google/jax/blob/f8d796939212fd2b3651c10c5e00f2f7503453c2/tests/random_test.py#L1550-L1555

I don't think we test custom_prng on github CI, but we have other test coverage for that that will catch it (and eventually custom_prng will be on by default)

2022-04-15 14:09 UTC, jakevdp commented on tests/random_test.py
> +    out = jnp.broadcast_to(key,        3)
Use a single space please

2022-04-15 16:35 UTC, jakevdp approved these changes
Thanks!

2022-04-15 17:19 UTC, merged