Added random.gnormal and random.ball.
jax-ml/jax pull request #10937
Opened 2022-06-01 21:31 UTC by carlosgmartin

2022-06-01 21:55 UTC, jakevdp requested changes
Looks good! A few comments below.

2022-06-01 21:55 UTC, jakevdp commented on jax/_src/random.py
> +  p = core.concrete_or_error(float, p, "The error occurred in jax.random.gnormal()")
I don't think we need this to be concrete; I believe `gamma` allows dynamic values for its shape parameter.

2022-06-01 21:55 UTC, jakevdp commented on jax/_src/random.py
> +  p = core.concrete_or_error(float, p, "The error occurred in jax.random.ball()")
Same here, no need for `p` to be concrete.

2022-06-01 21:55 UTC, jakevdp commented on tests/random_test.py
> +    samples = random.gnormal(key, p, shape, dtype)
We should test with and without `jit` (see the `rand`, `crand` pattern used elsewhere in this file)

2022-06-01 21:55 UTC, jakevdp commented on tests/random_test.py
> +    self.assertTrue(((jnp.abs(samples) ** p).sum(-1) <= 1).all())
Is there any statistic we can use to gauge the correctness of the samples? I've not looked closely at the algorithm, and this test doesn't provide a strong constraint. 

For example, am I right in thinking the radial CDF should equal the hyperspherical volume formula as a function of radius? We could compute that using gamma functions and compare it with a KS test.

2022-06-03 16:16 UTC, jakevdp requested changes
Looks great! One last comment

2022-06-03 16:16 UTC, jakevdp commented on tests/random_test.py
> +    samples = random.ball(key, d, p, shape, dtype)
Can we test both compiled and uncompiled versions here as well?

2022-06-03 19:08 UTC, jakevdp approved these changes
Looks great, thanks!

2022-06-03 19:09 UTC, jakevdp commented
Actually, looks like the readthedocs failure needs to be addressed. This is the error, which comes from a mis-formatted dosctring:
```
/home/docs/checkouts/readthedocs.org/user_builds/jax/checkouts/10937/jax/_src/random.py:docstring of jax._src.random.ball:17: WARNING: Inline emphasis start-string without end-string.
```

2022-06-03 19:26 UTC, carlosgmartin commented
> Actually, looks like the readthedocs failure needs to be addressed. This is the error, which comes from a mis-formatted dosctring:
> 
> ```
> /home/docs/checkouts/readthedocs.org/user_builds/jax/checkouts/10937/jax/_src/random.py:docstring of jax._src.random.ball:17: WARNING: Inline emphasis start-string without end-string.
> ```

2022-06-03 19:27 UTC, carlosgmartin commented
@jakevdp Fixed.

2022-06-03 21:15 UTC, jakevdp approved these changes
Looks great!

2022-06-03 23:44 UTC, merged