Added scipy.stats.gennorm.
jax-ml/jax pull request #11051
Opened 2022-06-10 00:00 UTC by carlosgmartin

2022-06-10 02:48 UTC, jakevdp requested changes
Looks great! Just minor comments

2022-06-10 02:48 UTC, jakevdp commented on jax/scipy/stats/gennorm.py
> +# Copyright 2020 Google LLC
2022

2022-06-10 02:48 UTC, jakevdp commented on jax/_src/scipy/stats/gennorm.py
> +# Copyright 2018 Google LLC
2022

2022-06-10 02:58 UTC, jakevdp approved these changes

2022-06-11 12:41 UTC, jakevdp commented
Merging failed because the new tests are failing on TPU due to floating point precision. We should be able to fix it by bumping the `rtol` in `CheckAgainstNumpy` from 0.0001 to 0.001

2022-06-14 16:11 UTC, jakevdp commented
Hi - just taking another look at this. Can you squash the two commits and rebase on the current main branch? Thanks!

2022-06-14 17:25 UTC, jakevdp approved these changes

2022-06-14 17:32 UTC, jakevdp commented
Looks like there are some conflicts... can you rebase against the updated main branch?

2022-06-14 18:12 UTC, carlosgmartin commented
@jakevdp Done.

2022-06-14 18:23 UTC, merged

2022-06-14 18:29 UTC, jakevdp commented
Thanks!