Call _check_arraylike for jnp.linalg & jnp.fft functions
jax-ml/jax pull request #12670
Opened 2022-10-05 19:35 UTC by jakevdp

Part of #7737

2022-10-06 17:33 UTC, sharadmv requested changes

2022-10-06 17:37 UTC, jakevdp commented on jax/_src/numpy/linalg.py
> +  _check_arraylike("jnp.linalg.cholesky", a)
Done

2022-10-06 17:37 UTC, jakevdp commented on jax/_src/third_party/numpy/linalg.py
> +  _check_arraylike('jnp.linalg.cond', *arrays)
Done

2022-10-06 17:39 UTC, sharadmv approved these changes

2022-10-06 23:18 UTC, jakevdp commented on CHANGELOG.md
> +  * Functions in {mod}`jax.numpy.linalg` and {mod}`jax.numpy.fft` now uniformly
Done

2022-10-27 03:41 UTC, soraros commented on jax/_src/numpy/fft.py
>    # TODO(jakevdp): call check_arraylike
This is no longer needed, right?

2022-10-27 16:01 UTC, jakevdp commented on jax/_src/numpy/fft.py
>    # TODO(jakevdp): call check_arraylike
Done, thanks

2022-10-31 16:38 UTC, merged