Fix `loc` and `scale` parameters in `scipy.logistic.*`. Add CDF and SF for several distributions.
jax-ml/jax pull request #14792
Opened 2023-03-05 23:41 UTC by b0nce

Starting with [this issue](https://github.com/google/jax/issues/12141) related to missing `loc` and `scale` parameters in logistic distribution (`jax.scipy.stats.logistic`), I've discovered that a lot of rv_continuous distributions lack `.cdf` and `.sf` methods.

Note that we can't guarantee exact match of results in Cauchy for `.isf` and `.ppf`, since `.tan` functions behave different in lax and numpy near divergence points (such as pi/2).

Complete list of changes:
 - Beta distribution: `.cdf`, `.logcdf` and `.sf` methods.
 - Cauchy distribution: `.cdf`, `.logcdf`, `.sf`, `.isf` and `.ppf` methods.
 - Chi squared distribution: `.cdf`, `.logcdf` and `.sf` methods.
 - Gamma distribution: `.cdf`, `.logcdf` and `.sf` methods.
 - Logistic distribution:  `loc` and `scale` parameters have been added to `logpdf`, `pdf`, `cdf`, `logcdf`, `isf`, `sf` and `ppf` methods.
 - Normal distribution: `.sf` and `.isf` methods.
 - Tests were skipped for `.cdf` methods due to similarities with `.logcdf` implementations.

2023-03-06 17:50 UTC, jakevdp requested changes
Thanks for the contribution - looks good!

Can we add tests for non-default values of `logistic` parameters to ensure they're implemented correctly? (I have concerns about `logpdf` below)

2023-03-06 17:50 UTC, jakevdp commented on docs/jax.scipy.rst
> +   logpdf as logpdf
Typo?

2023-03-06 17:50 UTC, jakevdp commented on jax/_src/scipy/stats/logistic.py
> +  return lax.div(lax.exp(logpdf(x, loc, scale)), scale)
Why is this not just `lax.exp(logpdf)`?

2023-03-06 18:13 UTC, b0nce commented on docs/jax.scipy.rst
> +   logpdf as logpdf
Yep, fixing

2023-03-06 18:13 UTC, b0nce commented on jax/_src/scipy/stats/logistic.py
> +  return lax.div(lax.exp(logpdf(x, loc, scale)), scale)
Because it's also a typo :)
Fixing

2023-03-07 02:48 UTC, jakevdp requested changes
Looks great, thanks!

The last thing we need is to squash all the changes into a single commit (see https://jax.readthedocs.io/en/latest/contributing.html#single-change-commits-and-pull-requests) and then we can get this merged. Thanks!

2023-03-07 06:58 UTC, b0nce commented
Oh, I thought this only applies to the first group of commits, so I squashed them into one and fixes into one 😅

2023-03-07 19:02 UTC, jakevdp approved these changes

2023-03-07 19:24 UTC, merged