Add kl_div and rel_entr functions
jax-ml/jax pull request #16656
Opened 2023-07-08 11:44 UTC by SalamanderXing

Their behavior is the same as functions in scipy.special. The only small difference is in rel_entr function, which unlike scipy.special does not take the optional parameter 'out', as JAX's arrays are immutable.

Resolves #16630

2023-07-10 19:57 UTC, jakevdp requested changes

2023-07-10 19:57 UTC, jakevdp commented on jax/_src/scipy/special.py
> +    (x,) = promote_args_inexact("gammaln", x)
Please revert the unrelated formatting changes.

2023-07-11 17:49 UTC, jakevdp requested changes
Great start, thanks for working on this! Two minor comments below, plus a couple other things to address:

- please add tests for the new functions. The appropriate place is probably here: https://github.com/google/jax/blob/main/tests/lax_scipy_special_functions_test.py Since this is using `select` statements, it will be important to test gradients of the functions as well: I think you've employed the double-where trick in both cases, so I don't think you should run into stray NaNs, but it's best to check!
- please add the new functions to the docs by listing them here: https://github.com/google/jax/blob/main/docs/jax.scipy.rst#jaxscipyspecial
- Once all this is finished, please squash your changes into a single commit (see https://jax.readthedocs.io/en/latest/contributing.html#single-change-commits-and-pull-requests and feel free to reach out if you need help with doing that in git)

Thanks!

2023-07-11 17:49 UTC, jakevdp commented on jax/_src/scipy/special.py
> +):
Annotate the return type with `-> Array`

2023-07-11 17:49 UTC, jakevdp commented on jax/_src/scipy/special.py
> +):
`-> Array` here as well

2023-07-24 10:33 UTC, SalamanderXing commented
Hi @jakevdp . I applied your requested changes but I also accidentally squashed several commits into one. Can you help me resolve this issue?

2023-07-24 15:36 UTC, jakevdp commented
You should be able to fix this by rebasing against the main branch. Assuming `origin` points to your repository, and `upstream` points to the main JAX repository, you can do this:
```
git checkout main
git pull upstream main
git checkout kl_div
git rebase main
git push origin +kl_div
```

2023-07-26 16:57 UTC, jakevdp commented
Looks good! The last thing we'll need is to squash all your changes into a single commit (see https://jax.readthedocs.io/en/latest/contributing.html#single-change-commits-and-pull-requests). Feel free to reach out if you need help with doing that in git.

2023-07-27 09:54 UTC, SalamanderXing commented
> Looks good! The last thing we'll need is to squash all your changes into a single commit (see https://jax.readthedocs.io/en/latest/contributing.html#single-change-commits-and-pull-requests). Feel free to reach out if you need help with doing that in git.

I should have done that, if that was unsuccessful please let me know how to squash them.

2023-07-27 13:44 UTC, jakevdp commented
Thanks - it looks like the squashing did not work: this pull request consists of five commits. Once you squash the changes into a single commit, the pull request should consist of one commit.

2023-07-27 13:45 UTC, jakevdp commented on jax/experimental/jax2tf/tests/jax_export_test.py
> +>>>>>>> 41620562d ([shape_poly] Improve error messages for shape assertions)
Looks like some git conflicts were not properly resolved.

2023-07-27 17:37 UTC, jakevdp approved these changes
Looks good!

2023-07-27 19:32 UTC, jakevdp commented on jax/_src/scipy/special.py
> +    one_zero_mask = lax.bitwise_and(lax.eq(p, 0.0), lax.ge(q, 0.0))
This is failing with a dtype mismatch with float32 inputs and `JAX_ENABLE_X64=1`.

If you want to use `lax` functions here, the input types must match exactly. You could use `zero = _lax_const(p, 0.0)` to ensure this is the case.

2023-07-27 19:33 UTC, jakevdp commented on jax/_src/scipy/special.py
> +    one_zero_mask = lax.bitwise_and(lax.eq(p, 0.0), lax.ge(q, 0.0))
same dtype mismatch issue here.

2023-07-27 21:38 UTC, jakevdp approved these changes
Thanks!

2023-07-27 23:44 UTC, merged

2023-07-28 07:47 UTC, SalamanderXing commented
> Thanks!

Thank you @jakevdp for patiently guiding me into this 👍