Setup compatibility testing to support the oldest supported libtpu ve…
jax-ml/jax pull request #18070
Opened 2023-10-11 22:05 UTC by sagyakwa

…rsion (12 weeks)

- A new matrix option was added to jaxlib-version matrix
- Expected to immediately fail due to strict jaxlib version check (requires libtpu to have the same API verison as jaxlib, fails otherwise)
- Due to expected failure, so chat will be sent when the jaxlib-version matrix is "nightly+oldest_supported_libtpu"

2023-10-12 21:26 UTC, skye requested changes

2023-10-12 21:26 UTC, skye commented on .github/workflows/cloud-tpu-ci-nightly.yml
> +      DATE_12_WEEKS_AGO: $(python3 -c "import datetime; print(datetime.date.today() - datetime.timedelta(weeks=12))")
Let's not actually use the rolling window to start and just specify the exact libtpu-nightly version that should be tested, and we can manually update that to start. We'll probably want to automatically roll the version in the future so we don't have to manually update it, but I wanna start on the conservative side (e.g. to make sure our version checks in the code line up with what we're testing)

2023-10-12 21:26 UTC, skye commented on .github/workflows/cloud-tpu-ci-nightly.yml
> +          env:
I don't think you can set an env var this way in the middle of the bash commands to run? Also this needs to be set for the test commands as well. You should just use a conditional in the regular env: block of the install + test steps (https://docs.github.com/en/actions/learn-github-actions/expressions#example)

2023-10-12 22:08 UTC, sagyakwa commented
@jying3 cc

2023-10-13 00:11 UTC, jyingl3 commented on .github/workflows/cloud-tpu-ci-nightly.yml
> +      LIBTPU_VERSION_DATE: 20230905
20230905 is too old. It needs to be after version 0.29 (https://github.com/openxla/xla/blob/main/xla/pjrt/c/CHANGELOG.md#029-sep-6-2023), and the earliest is 20230907. I think you can also try install and check the PJRT API version of the libtpu (through a jax built from source).

2023-10-17 23:09 UTC, skye approved these changes

2023-10-17 23:09 UTC, skye commented
Looks good! We should test this to double check it works, but we can commit and then try :)

2023-10-17 23:41 UTC, merged