Add Delta orthogonal initialization
jax-ml/jax pull request #1838
Opened 2019-12-10 17:04 UTC by SiuMath

Add the above initialization to jax/nn/initializers.py; see arXiv:1806.05393.

2019-12-17 01:40 UTC, jekbradbury requested changes
Sorry for the delay in reviewing (just got back from NeurIPS)!

2019-12-17 01:40 UTC, jekbradbury commented on jax/nn/initializers.py
> +      return ops.index_update(W, [(k-1)//2, ...], ortho_matrix)
This syntax doesn't work on Python 2 (and causes CI to fail, as you pointed out). Our `index_update` function is intended to accept any NumPy indexer/sequence of indicators, but a list isn't a valid syntactic environment for e.g. `2:4` or (on Python 2) `...`. In order to perform index_update indexing with indexers that aren't allowed outside an indexing environment, use `ops.index`:
```suggestion
      return ops.index_update(W, ops.index[(k-1)//2, ...], ortho_matrix)
```
(and similarly for the other two cases).

2019-12-17 02:24 UTC, SiuMath commented
Done!

2019-12-18 00:38 UTC, jekbradbury approved these changes

2019-12-18 00:38 UTC, merged