[PALLAS Triton] - Adding UINT8 dtype conversion from JAX to TRITON
jax-ml/jax pull request #18849
Opened 2023-12-06 19:36 UTC by DEKHTIARJonathan

Adding UINT8 dtype conversion from JAX to TRITON.

Allow support for `jax.numpy.bitwise_count`

```python
import jax
from jax.experimental import pallas as pl

# JAX
x = jnp.arange(8).astype(jnp.int32)
print(f"{jnp.bitwise_count(x)=}")   # jnp.argmax(x).dtype=dtype('uint8')

# PALLAS
def bitwise_count_kernel(x_ref, o_ref):
    x = pl.load(x_ref, ())
    out = jnp.bitwise_count(x)
    pl.store(o_ref, (), out)

@jax.jit
def exec_fn(_x):
    return pl.pallas_call(
        bitwise_count_kernel, 
        out_shape=jax.ShapeDtypeStruct(_x.shape, dtype=jnp.uint8 ),
        grid=1
    )(_x)

x = jnp.arange(8).astype(jnp.int32)
print(f"{exec_fn(x)=}")   # jnp.argmax(x).dtype=dtype('uint8')
```

Only works after the fix in this PR:

```python
>>> jnp.bitwise_count(x)=Array([0, 1, 1, 2, 1, 2, 2, 3], dtype=uint8)
>>> exec_fn(x)=Array([0, 1, 1, 2, 1, 2, 2, 3], dtype=uint8)
```

2023-12-06 19:36 UTC, DEKHTIARJonathan commented
@sharadmv

2023-12-07 03:25 UTC, sharadmv requested changes
Generally looks good but can you add a test to pallas_test?

2023-12-08 17:10 UTC, DEKHTIARJonathan commented
@sharadmv changes applied

2023-12-12 08:25 UTC, sharadmv commented
Sorry one last request: could you add a test that just tests the cast to i8 (as opposed to own that uses bincount)?

2025-02-10 17:38 UTC, closed without merging