Prevent silent overflow in lapack worker size calculations.
jax-ml/jax pull request #19288
Opened 2024-01-10 15:55 UTC by pearu

As in the title.

Addresses the issues of wrong results and crashes reported in https://github.com/google/jax/issues/10420, https://github.com/google/jax/issues/10411, etc.

2024-01-10 16:09 UTC, hawkinsp requested changes
This is a good improvement, although it would not catch the original issue, in which I think there was an integer overflow inside LAPACK from multiplying `m * n` when `m` and `n` were close to 2**16. To catch that we'd need some additional defensive checking limiting maximum sizes.

I would probably add that checking in Python here, if desired:
https://github.com/google/jax/blob/main/jaxlib/lapack.py


One other change is needed also. Please add:
```
    copts = ["-fexceptions"],
    features = ["-use_header_modules"],
```
to the `lapack_kernels` build target.
https://github.com/google/jax/blob/adf05d520a9ec95b2b05b6ba28b627ae34df4a02/jaxlib/cpu/BUILD#L32

By default we disable exceptions in our C++ builds, and they have to be enabled file by file. (Mostly we use `absl::Status` to communicate failure, but that's probably overkill here, where these workspace size functions are called by pybind11 wrappers and pybind11 wants failures as C++ exceptions.)

2024-01-10 16:25 UTC, hawkinsp commented
Actually you're probably right: the workspace size check would probably catch the original problem by itself. So only the BUILD file change is needed.

2024-01-10 16:41 UTC, pearu commented
> One other change is needed also. Please add: ...

Done. Thanks for the hint, @hawkinsp!

2024-01-10 17:22 UTC, hawkinsp approved these changes

2024-02-20 13:07 UTC, hawkinsp approved these changes

2024-02-20 20:43 UTC, merged