Added fallback cast to `float32` in case of integer overflow in `_fft_norm`
jax-ml/jax pull request #19378
Opened 2024-01-16 15:20 UTC by Micky774

Fixes https://github.com/google/jax/issues/18453

If a product would result in an integer overflow, now casts to `float32` to complete the calculation.

cc: @hawkinsp

2024-01-16 15:32 UTC, Micky774 commented
@jakevdp This PR should be a bit more sensible. Let me know what you think!

2024-02-01 14:33 UTC, Micky774 commented
cc: @pearu

2024-02-01 16:50 UTC, pearu requested changes
Added a suggestion that might be more efficient.

2024-02-01 16:50 UTC, pearu commented on jax/_src/numpy/fft.py
> +  if s.dtype.kind in "ui":
```suggestion
  if jnp.issubdtype(s.dtype, jnp.integer)
```

2024-02-01 16:50 UTC, pearu commented on jax/_src/numpy/fft.py
> +      s = s.astype(jnp.float32)
This looks very expensive to just determine if the conversion to float is required.

A simpler approach would be to always convert all integer inputs to float inputs to make sure that there will be no integer overflow:
```suggestion
    s = s.astype(jnp.float32)
```
or
```suggestion
    s = s.astype(jnp.float64 if jax.config.jax_enable_x64 else jnp.float32)
```

2024-02-01 19:41 UTC, jakevdp requested changes
Thanks for this! Comment below.

Also, we should add a regression test in `tests/fft_test.py`

2024-02-01 19:41 UTC, jakevdp commented on jax/_src/numpy/fft.py
> +
There's a utility for this
```python
from jax._src.numpy.util import promote_dtypes_inexact

...

s, = promote_dtypes_inexact(s)
```
You can call it regardless of the dtype of `s`

2024-02-05 17:59 UTC, jakevdp approved these changes
Looks good, thanks!

2024-02-05 18:02 UTC, jakevdp requested changes

2024-02-05 18:02 UTC, jakevdp commented on jax/_src/numpy/fft.py
> +from jax._src.numpy.util import promote_dtypes_inexact
Please add this to the existing imports from `jax._src.numpy.util`, a few lines above.

2024-02-05 19:20 UTC, jakevdp commented
Thanks! It looks like there are some conflicts with the main branch that must be resolved before we can proceed. Can you rebase (not merge) on `main`? Thanks!

2024-02-05 23:02 UTC, jakevdp approved these changes

2024-02-06 00:42 UTC, merged