Added pshuffle
jax-ml/jax pull request #1975
Opened 2020-01-10 01:34 UTC by Thenerdstation

I don't like how I need how I need to always use a list of tuples when doing a `ppermute`, and I end up using this `zip` trick every time. 

I am purposing a new `pshuffle` function as a simple wrapper to `ppermute` that uses the order of the integers as their implied destination index.

2020-01-10 02:00 UTC, skye requested changes
Love it! Just a few small comments on the test. I would even consider making this the API for ppermute and only having one API, but we can do that later since it's a breaking change.

2020-01-10 06:22 UTC, shoyer commented
> I would even consider making this the API for ppermute and only having one API, but we can do that later since it's a breaking change.

One use case from `ppermute` that this doesn't solve is omitting an index to get zeros instead. Though I'm sure we could squeeze that into `pshuffle` somehow, maybe by supporting `None` as indicating "no source"?

2020-01-10 16:49 UTC, skye commented
Oh good point, I didn't realize you could omit indices. `None` for no source/zero sounds very reasonable to me. (Doesn't need to be part of this PR of course.)

2020-01-10 22:59 UTC, Thenerdstation commented
Updated with comments!

2020-01-11 00:48 UTC, skye approved these changes

2020-01-11 00:49 UTC, merged