Add environment variable to remove debug information in MLIR module dump
jax-ml/jax pull request #20062
Opened 2024-03-04 16:01 UTC by Micky774

Closes https://github.com/google/jax/issues/18734

This PR introduces `JAX_ENABLE_IR_DEBUG` which mediates whether HLO modules are dumped with debug and location information for greatest detail, or whether that information is stripped for a sanitized dump.

2024-03-04 17:21 UTC, hawkinsp requested changes

2024-03-04 17:21 UTC, hawkinsp commented on jax/_src/interpreters/mlir.py
> +  'jax_enable_ir_debug', os.getenv('JAX_ENABLE_IR_DEBUG', "True"),
Perhaps `jax_include_debug_information_in_dumps` ?

It isn't immediately clear to me what `enable_ir_debug` means.

2024-04-04 13:54 UTC, Micky774 commented
@hawkinsp @jakevdp This should be ready

2024-04-04 14:09 UTC, hawkinsp approved these changes

2024-04-04 19:05 UTC, merged