minor modification for silu and swish func description
jax-ml/jax pull request #20108
Opened 2024-03-07 00:08 UTC by selamw1

Modify unfinished statement:
"SiLU (a.k.a." 
to complete statement:
"SiLU (aka swish) activation function." for both 'silu' and 'swish'.

Fixed by removing problematic characters.
https://jax.readthedocs.io/en/latest/jax.nn.html

2024-03-07 16:08 UTC, jakevdp requested changes
Looks good - please squash your changes into a single commit, then we can merge this. Thanks! (see https://jax.readthedocs.io/en/latest/contributing.html#single-change-commits-and-pull-requests)

2024-03-07 20:15 UTC, selamw1 commented
rebase is done to squash my changes into a single commit.
(only the last commit change is relevant)

2024-03-07 20:16 UTC, jakevdp commented
Sorry, it looks like you added a third commit. What we need is for the commits to be squashed into one, so that this branch only has a single commit beyond the `main` branch. Let me know if you need assistance with that.

2024-03-07 23:55 UTC, selamw1 commented
Sorry Jake, now commits are squashed into one.

2024-03-08 00:09 UTC, jakevdp approved these changes
Looks good, thanks!

2024-03-08 02:14 UTC, jakevdp commented
Fixes issue introduced in #20042

2024-03-08 02:37 UTC, merged