Implement column-pivoted QR via geqp3 (CPU lowering only)
jax-ml/jax pull request #20282
Opened 2024-03-16 08:22 UTC by tttc3

Provides a CPU only lowering of the column-pivoted QR decomposition in lapack  #12897. I would like to add GPU lowerings via MAGMA, but  I am unsure on the best way to optionally include this dependancy (as suggested here https://github.com/google/jax/issues/1259#issuecomment-845935966 ) into the jaxlib build.

2024-12-03 22:00 UTC, tttc3 commented
See ccb331707e80b16d89de6e5c9f2f89b87c1682ed for a reference implementation of a primitive that uses MAGMA.

2024-12-18 20:03 UTC, tttc3 commented
@dfm, would you be able to review this, and should I open a new draft PR for discussing a MAGMA based GPU implementation?

2025-01-02 15:35 UTC, dfm requested changes
Thanks for this, and sorry for the slow review! I wasn't actually working on JAX when you initially submitted the PR, and then didn't see it until you pinged me, so that was very useful :D 

This looks great overall. I've added an initial round of small inline comments. Please take a look at those, and then we can fire up the full CI run.

I think it's probably worth getting the details of the CPU implementation and the frontend API sorted out before getting into the MAGMA implementation too deeply, but I'm very happy to review that PR once we get there too. Thanks again!!

2025-01-02 15:35 UTC, dfm commented on jax/_src/lax/linalg.py
> +                          # operand_output_aliases={0: 0})
Should this be:

```suggestion
                          operand_output_aliases={0: 0, 1: 1})
```

2025-01-02 15:35 UTC, dfm commented on jax/_src/lax/linalg.py
> +    p = operand.update(dtyp=np.dtype(np.int32))
This won't work in general (`update` won't be defined if the input isn't a `ShapedArray`). The standard approach (e.g. see the abstract eval rule for LU) seems to be to just return the operand for `p` as well, even though that's nonsense. I wonder if @hawkinsp, @mattjj, or anyone else can chime in about what semantics we would want for an abstract eval called with non-`ShapedArray` inputs?

2025-01-02 15:35 UTC, dfm commented on jax/_src/lax/linalg.py
> +    return (q, r, p), (dq, dr, dp)
It seems like pivoting should affect the tangents as well. Can you add more details about why the JVP rule doesn't need to change with pivoting?

2025-01-02 15:35 UTC, dfm commented on jaxlib/cpu/lapack_kernels.cc
> +  CopyIfDiffBuffer(jpvt, jpvt_out);
Note: this is what lets us use input-output aliasing above!

2025-01-02 15:35 UTC, dfm commented on jaxlib/cpu/lapack_kernels.cc
Nit: The indenting is all a bit wonky in this file. You might be able to run `clang-format` with Google style, or some other automatic formatter on your change to get consistent indenting. Otherwise, can you go through and try to clean it up a bit by hand?

2025-01-02 15:35 UTC, dfm commented on tests/linalg_test.py
> +  def testScipyQrModes(self, shape, dtype, mode, pivoting):
This probably needs to be skipped when `pivoting is True` unless the test is running on CPU. You can probably use something like [`if not jtu.test_device_matches(["cpu"])`](https://github.com/jax-ml/jax/blob/ac817b48ca90e08da382b1fe674fa58122b7dadd/jax/_src/test_util.py#L459C5-L459C24).

2025-01-02 15:35 UTC, dfm commented on tests/linalg_test.py
> +  def testScipyQrModes(self, shape, dtype, mode, pivoting):
Oh and also, this should be conditioned on the version of `jaxlib` too, since the currently released backend doesn't support this FFI call. You can use the [`jtu.jaxlib_version`](https://github.com/jax-ml/jax/blob/ac817b48ca90e08da382b1fe674fa58122b7dadd/jax/_src/test_util.py#L339C5-L339C19) utility for conditioning on that.

2025-01-02 16:12 UTC, tttc3 commented on jax/_src/lax/linalg.py
> +    return (q, r, p), (dq, dr, dp)
I believe the impact of pivoting on the tangents is captured entirely by the `q` and `r` values that are returned from `qr_p.bind(...)`, and that tangent validity is subject to, at worst, the same assumptions as the non-pivoted case (that `x` is  of full column-rank `k = min(m, n)`).

However, this is not my area of expertise, so I may be missing something.

2025-01-02 18:22 UTC, tttc3 commented
Thanks for the review! In the interest of reducing code duplication, would it be preferred if `PivotingQrFactorizationComplex` was removed, and `if constexpr` used to handle the complex case (where the only difference is to allocate and pass `rwork`)? I.E. something similar to what is done for the `SVD`.

2025-01-03 16:02 UTC, dfm commented on jax/_src/lax/linalg.py
> +    return (q, r, p), (dq, dr, dp)
In the case where `pivoting=True`, I would expect `dx` to be indexed by `p`. If I understand the behavior properly, `x[..., p] = q @ r`, so we'll want to use `dx[..., p]` when propagating the tangents, right?

Relatedly: it would be good to add some test coverage for AD when `pivoting=True`. This might also help pointing us of the right thing to do here! Here are the current AD tests for QR which might be a useful place to start:

https://github.com/jax-ml/jax/blob/0f4677bcf68f92364d7e8bf9299ee659e2745c20/tests/linalg_test.py#L1025-L1032

2025-01-03 16:03 UTC, dfm approved these changes
I'm approving this PR to trigger the full test suite, but I think we still want to iterate on the JVP question!

2025-01-03 17:39 UTC, tttc3 commented on jax/_src/lax/linalg.py
> +    return (q, r, p), (dq, dr, dp)
Ah yes, you are right! Because the Numpy API doesn't support pivoting, I will add a `check_jvp` statement to the end of `testScipyQrModes`.

2025-01-06 14:59 UTC, dfm commented
Thanks! This all looks good to me now! Can you rebase this PR onto the `main` branch, squashing your commits into one? Then I'll work on getting it merged. Thanks again!

2025-01-06 14:59 UTC, dfm commented
PS. Please ping me once you've rebased, I don't get notified for pushes!

2025-01-06 17:12 UTC, tttc3 commented
@dfm I've rebased and re-added the type hint overloads for `jax.scipy.linalg.qr`.

2025-01-09 13:50 UTC, dfm approved these changes

2025-01-09 14:39 UTC, dfm commented
Thanks! It looks like this causes a couple of failures for tests that aren't run as part of the GitHub CI. Can you add the new `geqp3` primitive to this list:

https://github.com/jax-ml/jax/blob/640cb009f10118358263d6ce1476962bb0b60cc5/jax/experimental/jax2tf/jax2tf.py#L1477

And then only run the new JVP tests when `pivoting is True`?

After you make those changes, please squash the commits and rebase onto the current main. Then we should be good to go!

Thanks again for this!!

2025-01-09 15:08 UTC, dfm approved these changes

2025-01-09 15:44 UTC, dfm commented on tests/linalg_test.py
> +    full_matrices = mode in ["full", "r"]
I'm still seeing failures here when `mode == "r"`. Perhaps we should just test for `mode == "full"`? Regardless, we might also want to "undo" the pivoting in `qr_and_mul` so that any changes in the pivoting caused by the finite difference used in the check doesn't lead to unexpected results. What do you think?

2025-01-09 16:23 UTC, tttc3 commented on tests/linalg_test.py
> +    full_matrices = mode in ["full", "r"]
The `mode=="full"` case should be sufficient on its own, but we can easily include the `mode=="economic"` case as well so I'm happy to just ignore `mode=="r"` (this is implicitly tested in the other modes anyway). I'm not sure about the pivoting, but I think you are probably right - I will think about it and let you know later.

2025-01-09 20:47 UTC, tttc3 commented on tests/linalg_test.py
> +    full_matrices = mode in ["full", "r"]
I've updated `qr_and_mul` to "undo" the pivoting - it now expresses the identity function, like in the numpy tests and should be more robust.

2025-01-09 21:02 UTC, dfm approved these changes

2025-01-10 16:02 UTC, merged