DOC: Improve documentation for `jnp.fliplr` and `jnp.flipud`
jax-ml/jax pull request #21692
Opened 2024-06-06 08:09 UTC by rajasekharporeddy

Part of #21461

2024-06-06 16:55 UTC, jakevdp commented on jax/_src/numpy/lax_numpy.py
> +    m: Array.
array with at least two dimensions

2024-06-06 16:55 UTC, jakevdp commented on jax/_src/numpy/lax_numpy.py
> +    m: Array.
Array with at least one dimension

2024-06-07 00:49 UTC, rajasekharporeddy commented on jax/_src/numpy/lax_numpy.py
> +    m: Array.
Done

2024-06-07 00:49 UTC, rajasekharporeddy commented on jax/_src/numpy/lax_numpy.py
> +    m: Array.
Done

2024-06-07 03:23 UTC, jakevdp requested changes

2024-06-07 03:23 UTC, jakevdp commented on jax/_src/numpy/lax_numpy.py
> +    m: Array with atleast two dimenssions.
```suggestion
    m: Array with at least two dimensions.
```

2024-06-07 03:23 UTC, jakevdp commented on jax/_src/numpy/lax_numpy.py
> +    m: Array with atleast one dimension.
```suggestion
    m: Array with at least one dimension.
```

2024-06-07 04:10 UTC, rajasekharporeddy commented on jax/_src/numpy/lax_numpy.py
> +    m: Array with atleast two dimenssions.
Done

2024-06-07 04:10 UTC, rajasekharporeddy commented on jax/_src/numpy/lax_numpy.py
> +    m: Array with atleast one dimension.
Done

2024-06-07 16:09 UTC, jakevdp approved these changes
Thanks!

2024-06-07 17:15 UTC, merged