DOC: Update jnp.mean doc
jax-ml/jax pull request #22132
Opened 2024-06-27 06:38 UTC by rajasekharporeddy

Updates the doc of `jnp.mean` and also fixes a typo in `jnp.sum` doc.
 
Part of #21461.

2024-06-28 16:39 UTC, jakevdp requested changes

2024-06-28 16:39 UTC, jakevdp commented on jax/_src/numpy/reductions.py
> +    An array of the sum along the given axis.
```suggestion
    An array of the mean along the given axis.
```

2024-06-28 16:39 UTC, jakevdp commented on jax/_src/numpy/reductions.py
> +    ...                    [1, 1, 0, 1]])
Add `dtype=bool` for clarity.

2024-07-01 06:38 UTC, rajasekharporeddy commented on jax/_src/numpy/reductions.py
> +    axis: int or array, default=None. Axis along which the mean to be computed.
Done

2024-07-01 06:38 UTC, rajasekharporeddy commented on jax/_src/numpy/reductions.py
> +    where: int or array, default=None. The elements to be used in the mean. Array
Done

2024-07-01 06:38 UTC, rajasekharporeddy commented on jax/_src/numpy/reductions.py
> +    An array of the sum along the given axis.
Done

2024-07-01 06:38 UTC, rajasekharporeddy commented on jax/_src/numpy/reductions.py
> +    ...                    [1, 1, 0, 1]])
Done

2024-07-01 06:40 UTC, rajasekharporeddy commented
Implemented the review changes and squashed into single commit.

2024-07-01 13:46 UTC, dfm approved these changes
Looks good - thanks!

2024-07-01 14:30 UTC, merged