better log2 doc
jax-ml/jax pull request #22191
Opened 2024-06-28 22:29 UTC by pkgoogle

better log2 doc

Part of https://github.com/google/jax/issues/21461

2024-06-28 22:41 UTC, jakevdp commented on jax/_src/numpy/ufuncs.py
> +    Array([0.49999994+1.13309j, 0.        +4.53236j, 0.        +0.j     ,
This complex one is going to be problematic due to float accuracy; I'd probably just remove it.

2024-06-28 22:52 UTC, jakevdp commented
Thanks! If you can squash the changes into a single commit, then we'll get this merged!

2024-07-01 20:32 UTC, dfm requested changes
I have one last quick request here, then let's get this merged. Thanks!

2024-07-01 20:32 UTC, dfm commented on jax/_src/numpy/ufuncs.py
> +    Array([nan, nan, nan, nan, nan, nan], dtype=float32)
I'm not sure that this example really adds much to the discussion. I'd recommend that we remove it!

2024-07-02 17:53 UTC, dfm approved these changes
Looks good - thanks!

2024-07-03 12:26 UTC, merged