DOC: Improved docs for `jnp.nanmin` and `jnp.nanmax`
jax-ml/jax pull request #22366
Opened 2024-07-10 05:17 UTC by rajasekharporeddy

Part of #21461

2024-07-10 14:06 UTC, dfm requested changes
Thanks! Tiny changes requested.

2024-07-10 14:06 UTC, dfm commented on jax/_src/numpy/reductions.py
> +    axis: int or array, default=None. Axis along which the minimum is computed.
```suggestion
    axis: int or sequence of ints, default=None. Axis along which the minimum is computed.
```

2024-07-10 14:06 UTC, dfm commented on jax/_src/numpy/reductions.py
> +    where: int or array of boolean dtype, default=None. The elements to be used
```suggestion
    where: array of boolean dtype, default=None. The elements to be used
```

2024-07-10 14:06 UTC, dfm commented on jax/_src/numpy/reductions.py
> +    axis: int or array, default=None. Axis along which the maximum is computed.
```suggestion
    axis: int or sequence of ints, default=None. Axis along which the maximum is computed.
```

2024-07-10 14:06 UTC, dfm commented on jax/_src/numpy/reductions.py
> +    where: int or array of boolean dtype, default=None. The elements to be used
```suggestion
    where: array of boolean dtype, default=None. The elements to be used
```

2024-07-10 14:27 UTC, rajasekharporeddy commented on jax/_src/numpy/reductions.py
> +    axis: int or array, default=None. Axis along which the minimum is computed.
Done

2024-07-10 14:27 UTC, rajasekharporeddy commented on jax/_src/numpy/reductions.py
> +    where: int or array of boolean dtype, default=None. The elements to be used
Done

2024-07-10 14:27 UTC, rajasekharporeddy commented on jax/_src/numpy/reductions.py
> +    axis: int or array, default=None. Axis along which the maximum is computed.
Done

2024-07-10 14:27 UTC, rajasekharporeddy commented on jax/_src/numpy/reductions.py
> +    where: int or array of boolean dtype, default=None. The elements to be used
Done

2024-07-10 14:29 UTC, rajasekharporeddy commented
Modified the docstrings and squashed the commits into one.

2024-07-11 16:42 UTC, dfm approved these changes

2024-07-11 17:15 UTC, merged