DOC: Improved docs for `jnp.nansum` and `nanprod`
jax-ml/jax pull request #22369
Opened 2024-07-10 08:41 UTC by rajasekharporeddy

Part of #21461.

2024-07-10 14:03 UTC, dfm requested changes
Thanks! I left a few small comments, otherwise looks great!

2024-07-10 14:03 UTC, dfm commented on jax/_src/numpy/reductions.py
> +    axis: int or array, default=None. Axis along which the sum is computed. If
```suggestion
    axis: int or sequence of ints, default=None. Axis along which the sum is computed. If
```

2024-07-10 14:03 UTC, dfm commented on jax/_src/numpy/reductions.py
> +    where: int or array of boolean dtype, default=None. The elements to be used
```suggestion
    where: array of boolean dtype, default=None. The elements to be used
```

2024-07-10 14:03 UTC, dfm commented on jax/_src/numpy/reductions.py
> +    >>> nan= jnp.nan
```suggestion
    >>> nan = jnp.nan
```

2024-07-10 14:03 UTC, dfm commented on jax/_src/numpy/reductions.py
> +    where: int or array of boolean dtype, default=None. The elements to be used
```suggestion
    where: array of boolean dtype, default=None. The elements to be used
```

2024-07-10 14:03 UTC, dfm commented on jax/_src/numpy/reductions.py
> +    axis: int or array, default=None. Axis along which the product is computed.
```suggestion
    axis: int or sequence of ints, default=None. Axis along which the product is computed.
```

2024-07-10 14:03 UTC, dfm commented on jax/_src/numpy/reductions.py
> +    >>> nan= jnp.nan
```suggestion
    >>> nan = jnp.nan
```

2024-07-10 14:32 UTC, rajasekharporeddy commented on jax/_src/numpy/reductions.py
> +    axis: int or array, default=None. Axis along which the sum is computed. If
Done

2024-07-10 14:32 UTC, rajasekharporeddy commented on jax/_src/numpy/reductions.py
> +    where: int or array of boolean dtype, default=None. The elements to be used
Done

2024-07-10 14:32 UTC, rajasekharporeddy commented on jax/_src/numpy/reductions.py
> +    >>> nan= jnp.nan
Done

2024-07-10 14:32 UTC, rajasekharporeddy commented on jax/_src/numpy/reductions.py
> +    where: int or array of boolean dtype, default=None. The elements to be used
Done

2024-07-10 14:32 UTC, rajasekharporeddy commented on jax/_src/numpy/reductions.py
> +    axis: int or array, default=None. Axis along which the product is computed.
Done

2024-07-10 14:32 UTC, rajasekharporeddy commented on jax/_src/numpy/reductions.py
> +    >>> nan= jnp.nan
Done

2024-07-10 14:33 UTC, rajasekharporeddy commented
Modified the docstrings and squashed the commits into one.

2024-07-11 16:43 UTC, dfm approved these changes

2024-07-11 17:27 UTC, dfm commented
Since #22366 was merged, it looks like we can't merge until you rebase onto `main`. Can you do that now? Thanks!

2024-07-11 17:32 UTC, rajasekharporeddy commented
Rebased onto main.

2024-07-11 19:50 UTC, merged