Update installation instructions
jax-ml/jax pull request #22410
Opened 2024-07-12 00:05 UTC by garymm

Apple GPUs and Mac x86_64 is a non-existent combination. Mac x86_64 with AMD GPU is supported.

It's a bit of a confusing situation so hard to summarize, but hopefully this is more accurate and less confusing

2024-07-12 00:17 UTC, hawkinsp requested changes
Thanks for the PR.

There's a second copy of this table in the full installation instructions: https://jax.readthedocs.io/en/latest/installation.html#supported-platforms

Mind updating it also?

2024-07-12 00:17 UTC, hawkinsp commented on README.md
> +| AMD GPU    | experimental | no            | experimental | n/a          | no             | no                  |
Ah, I think I see the confusion. Here the issue is that "AMD GPU" was meant to mean "ROCM" and "Apple GPU" was meant to mean "Metal". I agree, this is probably clearer.

2024-07-12 00:17 UTC, hawkinsp commented on README.md
> +| Mac             | Follow [Apple's instructions](https://developer.apple.com/metal/jax/).                                          |
Perhaps

Apple or AMD GPU (Mac)

2024-07-12 00:17 UTC, hawkinsp commented on README.md
> +| Mac             | Follow [Apple's instructions](https://developer.apple.com/metal/jax/).                                          |
Or just Mac GPU

2024-07-12 19:03 UTC, garymm commented
Updated the installation page as well.

2024-09-27 00:12 UTC, garymm commented
@hawkinsp this is ready I believe

2024-10-21 12:53 UTC, hawkinsp commented
(And you'll need to sync on top of head)

2024-10-21 17:20 UTC, garymm commented
@hawkinsp done.

2024-10-21 20:55 UTC, hawkinsp approved these changes
Thanks!

2024-10-21 21:05 UTC, merged