[cuDNN SDPA] add sm86/sm89 flash attention support
jax-ml/jax pull request #22605
Opened 2024-07-23 17:57 UTC by Cjkkkk

remove sm80/sm90 only constraint to include sm86/sm89 as well since non flash version attention is removed from cuDNN SDPA and this constraint can be relaxed.

2024-07-23 17:58 UTC, Cjkkkk commented
@superbobry could you help review this? related discussion: https://github.com/google/jax/issues/22546

2024-07-24 12:17 UTC, superbobry requested changes

2024-07-24 12:17 UTC, superbobry commented on jax/_src/cudnn/fused_attention_stablehlo.py
> +  jtu.is_cuda_compute_capability_at_least("8.0")
`jtu` is for testing. Perhaps inline it here instead?

Note also that atm you aren't asserting anything.

2024-07-24 12:17 UTC, superbobry commented on tests/fused_attention_stablehlo_test.py
> +      jtu.is_cuda_compute_capability_at_least("8.0")
```
if not jtu.is_cuda_compute_capability_at_least("8.0"):
  self.skipTest(...)
```

2024-07-24 12:17 UTC, superbobry commented on tests/fused_attention_stablehlo_test.py
> +      jtu.is_cuda_compute_capability_at_least("9.0")
As above.

2024-07-24 20:44 UTC, Cjkkkk commented
@superbobry all comments addressed and rebased. Could you take an another look? Thanks!

2024-07-24 21:15 UTC, Cjkkkk commented
Rebased again to support blackwell: https://github.com/google/jax/pull/22608

2024-07-25 09:31 UTC, superbobry approved these changes

2024-07-25 10:32 UTC, merged

2024-07-31 16:43 UTC, MasterSkepticista commented
Apologies if this isn't the relevant PR to ask: Is there a plan to add `dropout` capability on `attn_weights` in the SDPA API?