DOC: Better docs for `jnp.fft.hfft` and `jnp.fft.ihfft`
jax-ml/jax pull request #22834
Opened 2024-08-02 10:05 UTC by rajasekharporeddy

Part of #21461

2024-08-02 10:42 UTC, dfm requested changes
Thanks! Small comments inline.

2024-08-02 10:42 UTC, dfm commented on jax/_src/numpy/fft.py
> +  Examples:
Could we add an example where the input data are complex? I think we could compute an appropriate input using `rfft`?

2024-08-02 10:42 UTC, dfm commented on jax/_src/numpy/fft.py
> +    along ``axis``.
Is it worth stating that the output will always be real?

2024-08-02 10:42 UTC, dfm commented on jax/_src/numpy/fft.py
> +    This is equivalent to computing ``jnp.fft.fft`` of the following array ``x1``:
Not quite equivalent because of the `dtype`s!

2024-08-02 16:02 UTC, rajasekharporeddy commented on jax/_src/numpy/fft.py
> +  Examples:
Thanks. Included the example with complex input.

2024-08-02 16:03 UTC, rajasekharporeddy commented on jax/_src/numpy/fft.py
> +    along ``axis``.
Written it as "A real-vlaued array"

2024-08-02 16:04 UTC, rajasekharporeddy commented on jax/_src/numpy/fft.py
> +    This is equivalent to computing ``jnp.fft.fft`` of the following array ``x1``:
Modified the statement as "This value is equal to the real component of the discrete Fourier transform
    of the following array ``x1`` computed using ``jnp.fft.fft``."

2024-08-05 10:10 UTC, dfm commented
Looks good - thanks! Can you squash the commits?

2024-08-05 16:24 UTC, rajasekharporeddy commented
Thanks! Squashed into single commit

2024-08-06 09:11 UTC, dfm approved these changes
Thanks!

2024-08-06 17:47 UTC, merged