Revert to nvtx_kern_sum to get correct profiling info and adding post processing logic
jax-ml/jax pull request #23467
Opened 2024-09-05 20:42 UTC by abhinavgoel95

cc @mgoldfarb-nvidia 
We can add memory kernel times once we figure out how to get that data reliably from nsys

2024-09-05 20:48 UTC, hawkinsp approved these changes
I didn't review this that closely, but I'm presuming you tested this and found it to work better.

2024-09-05 20:54 UTC, hawkinsp commented
mypy is sad, see the lint_and_typecheck result.

2024-09-06 13:15 UTC, hawkinsp requested changes
mypy fix needed to merge this.

2024-09-16 22:13 UTC, abhinavgoel95 commented
I will fix this and ask for another review. Thanks.

2024-09-18 21:59 UTC, abhinavgoel95 commented on jax/tools/pgo_nsys_converter.py
> +  parser.add_argument("--post_process", help="post process pbtxt to get max cost value for each instruction", action="store_true")
@abhinavgoel95  to make this default true.

2024-09-25 22:53 UTC, abhinavgoel95 commented
@hawkinsp where can I see the mypy/linter errors?

2024-09-25 23:40 UTC, hawkinsp commented
I just reapproved the CI runs (unless you're a collaborator on the repository it needs approval to run CI  — I'm surprised you're not, actually, let me know if you want to be added). Lint/mypy errors should show up now.

(You can reproduce these locally by using `pre-commit` in your source tree.)

2024-10-07 16:40 UTC, abhinavgoel95 commented
@hawkinsp yeah, would like to become a collaborator. 
Fixed the mypy issues, could you re-approve the CI run?

2024-10-14 23:29 UTC, merged