Fix jax.numpy.linalg.inv with shape polymorphism
jax-ml/jax pull request #23656
Opened 2024-09-16 16:07 UTC by tchatow

Fixes https://github.com/google/jax/issues/22489#issuecomment-2338868969

2024-09-17 08:22 UTC, gnecula approved these changes
Thank you!

2024-09-17 08:31 UTC, gnecula requested changes

2024-09-17 08:31 UTC, gnecula commented on tests/shape_poly_test.py
> +  def test_linalg_inv_bug_22489(self):
Please move this test to be part of_POLY_SHAPE_TEST_HARNESSES, e.g., search for how "linspace" is tested. That way the test follows the same pattern as others and it is more complete (it actually runs the code).

2024-09-17 18:40 UTC, dfm commented
You should be able to still add the test by adding:

```python
override_jax_config_flags={"jax_export_ignore_forward_compatibility": True}
```

to the test harness like we do for the LU test just a couple below the one you've added. I'm pretty sure that'll be enough!

2024-09-17 19:25 UTC, tchatow commented
Got it. Unfortunately I couldn't figure out a non-trivial random test case, since neither of the ways I can think of to check for invertibility - `jnp.linalg.cond` or `jnp.linalg.matrix_rank` work with shape polymorphism.

2024-10-02 08:09 UTC, gnecula approved these changes

2024-10-07 10:38 UTC, merged