Add CI workflow to check JAX distibuted initialize within K8s jobsets
jax-ml/jax pull request #24197
Opened 2024-10-08 19:14 UTC by yhtang

2024-10-21 16:48 UTC, yhtang commented
@hawkinsp PTAL when convenient. Thanks!

2025-03-17 18:01 UTC, MichaelHudgins requested changes
There a few changes to be able to review properly.  This also may not be something that should run as a presubmit all the time.

2025-03-17 18:03 UTC, MichaelHudgins commented on .github/workflows/k8s.yaml
> +      TAG: ${{ steps.metadata.outputs.tags }}
According to actions lint this is causing the file to error out with property undefined

2025-03-17 18:30 UTC, yhtang commented on .github/workflows/k8s.yaml
> +  pull-requests: read
removed

2025-03-17 18:31 UTC, yhtang commented on .github/workflows/k8s.yaml
> +      TAG: ${{ steps.metadata.outputs.tags }}
This is now removed. The Action is properly running in my own fork now: https://github.com/yhtang/jax/actions/runs/13907097350

2025-03-21 15:54 UTC, MichaelHudgins commented
The test itself and workflow looks fine to me, we will need to allow list the minikube reusable workflow.  I personally don't see much risk in it. 

 I would like a member of the JAX core team(@hawkinsp maybe) to speak to the acceptance of a specific e2e test such as this.  I could see it being extended in the future to test a few more of the k8s operations that don't have the best of coverage externally right now.

2025-04-02 17:16 UTC, skye commented
Me and @mattjj approve this. We haven't looked in detail, but if Michael is happy with it, let's give it a try. We can revisit if we have trouble keeping this green. We do recognize this is different from existing CI tests.

2025-04-02 17:16 UTC, skye approved these changes

2025-04-02 22:33 UTC, merged