Fix argmin docstring to not say "maximum"
jax-ml/jax pull request #24657
Opened 2024-11-01 06:01 UTC by dymil

I presume somebody was copy-pasting...

2024-11-01 10:48 UTC, dfm approved these changes
Thanks!

2024-11-01 12:42 UTC, jakevdp requested changes

2024-11-01 12:42 UTC, jakevdp commented on jax/_src/numpy/lax_numpy.py
> +    - :func:`jax.numpy.argmax`: return the index of the minimum value.
This one should say `maximum`

2024-11-01 13:48 UTC, dfm commented on jax/_src/numpy/lax_numpy.py
> +    - :func:`jax.numpy.argmax`: return the index of the minimum value.
whoops - good catch! Thanks, @jakevdp.

2024-11-08 16:21 UTC, dfm approved these changes

2024-11-08 17:48 UTC, merged