Added CI job with TSAN and free-threading
jax-ml/jax pull request #24898
Opened 2024-11-14 16:39 UTC by vfdev-5

Description:
- added CI job with TSAN and free-threading
- temporarily updated WORKSPACE, this can be removed once merged: https://github.com/openxla/xla/pull/19346

2025-01-17 01:11 UTC, hawkinsp requested changes
Probably worth getting this submitted soon.

2025-01-17 01:11 UTC, hawkinsp commented on .github/workflows/tsan.yaml
> +          python build/build.py build --wheels=jaxlib \
We can simplify this now. Add `--configure_only` to the `build` command line so this sets up the bazel configuration but does not build anything.
 
Also add `--python_version=3.13-ft`

2025-01-17 01:11 UTC, hawkinsp commented on .github/workflows/tsan.yaml
> +          ./bazel test \
We can then build and run the tests with `bazel` like this:

```
bazel test //tests:cpu_tests --test_env=TSAN_OPTIONS=halt_on_error=1,suppressions=/path/to/suppressions --test_env=JAX_TEST_NUM_THREADS=8
``` 

perhaps with a couple of the other environment variables.

2025-01-17 01:11 UTC, hawkinsp commented on tests/api_test.py
>    def test_concurrent_device_get_and_put(self):
Revert all the test changes from this PR.

2025-01-17 01:11 UTC, hawkinsp commented on .github/workflows/tsan.yaml
> +          ${GITHUB_WORKSPACE}/cpython-tsan/bin/python3 -m venv ${GITHUB_WORKSPACE}/venv
The venv won't be needed if we use bazel to run the tests.

2025-01-17 01:11 UTC, hawkinsp commented on .github/workflows/tsan.yaml
> +            --bazel_options=--@rules_python//python/config_settings:py_freethreaded="yes" \
No longer needed.

2025-01-17 01:11 UTC, hawkinsp commented on .github/workflows/tsan.yaml
> +          ref: v3.13.1
I might pick the tip of the 3.13 branch rather than the 3.13.1 release for the moment.

2025-01-17 01:11 UTC, hawkinsp commented on .github/workflows/tsan.yaml
> +
It might be worth using a nightly numpy here, which requires amending the requirements file.

2025-01-17 08:59 UTC, vfdev-5 commented on .github/workflows/tsan.yaml
> +          ./bazel test \
I would split build and test steps

2025-01-17 15:53 UTC, hawkinsp commented on .github/workflows/tsan.yaml
> +          ./bazel test \
No, you shouldn't, because that's actually slower.

2025-01-17 15:56 UTC, hawkinsp requested changes

2025-01-17 16:05 UTC, vfdev-5 commented on build/requirements_lock_3_13_ft.txt
> +--extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
Oh, that's true, sorry

2025-01-17 16:17 UTC, hawkinsp commented on .github/workflows/tsan.yaml
> +          export PYTHON_GIL=0
Just make it `--repo_env=PYTHON_GIL=0` then?

2025-01-17 16:17 UTC, hawkinsp commented on .github/workflows/tsan.yaml
> +          export PYTHON_GIL=0
Also the comment about the warning here is stale. We fixed that long ago.

2025-01-17 16:19 UTC, hawkinsp commented on .github/workflows/tsan.yaml
> +              --//jax:build_jaxlib=false \
Remove build_jaxlib=false

2025-01-17 16:19 UTC, hawkinsp commented on .github/workflows/tsan.yaml
> +              --nocache_test_results \
Remove, not needed.

2025-01-17 16:19 UTC, hawkinsp commented on .github/workflows/tsan.yaml
> +              --test_output=all \
I'd only output for errors, probably.

2025-01-28 15:26 UTC, hawkinsp approved these changes

2025-01-28 21:38 UTC, merged

2025-01-28 21:49 UTC, vfdev-5 commented on .github/workflows/tsan.yaml
> +    #   - main
Actually, I may had to uncomment this...