Refactor xla_bridge.py to do all backend caching itself.
jax-ml/jax pull request #2835
Opened 2020-04-25 01:53 UTC by skye

This is working towards removing backend caching from the XLA client,
making jax responsible for caching instead. This will ultimately
simplify the backend creation and caching logic.

Prior to this change, each backend factory was expected to memoize its
returned backends. xla_bridge.get_backend() was already memoized, but
the extra caching layer was necessary to make get_backend(None) and
get_backend(<default backend string>) return the same Backend object.

This change achieves the same effect in xla_bridge alone via the
following changes:

1. Creating specific backend factories for every platform in
   xla_bridge, instead of the rough groupings denoted by the
   --jax_xla_backend flag. This allows us to move the default backend
   logic to xla_bridge.

2. Initializing all registered backends on the first get_backend()
   call. This allows xla_bridge to know which backends are available,
   e.g. to pick a default, warn if no GPU/TPU is available.

2020-04-25 01:53 UTC, skye commented
Marking as draft until I can verify this will work inside google as well.

2020-06-01 22:09 UTC, hawkinsp requested changes

2020-06-01 22:09 UTC, hawkinsp commented on jax/lib/xla_bridge.py
>      raise RuntimeError("No local XLA backends found.")
This message string seems misleading given you call this function from multiple places.

2020-06-01 22:09 UTC, hawkinsp commented on jax/lib/xla_bridge.py
> +      # TODO(skye): remove name parameter once all backend factories create a
Should this just be:
```
# TODO(skye): remove the name parameter
```
because there's no condition on it, it just needs doing now.

2021-05-26 21:08 UTC, hawkinsp commented
Closing; https://github.com/google/jax/pull/6829 will replace this PR.

2021-05-26 21:08 UTC, closed without merging