Implemented numpy setxor1d
jax-ml/jax pull request #2943
Opened 2020-05-03 19:50 UTC by joschkabraun

This is an implementation of [numpy.setxor1d](https://docs.scipy.org/doc/numpy/reference/generated/numpy.setxor1d.html) from issue #70 (and #2078). It follows the same structure as the original implementation with changes for Jax compatibility.

np.setxor1d is intrinsically hard to make jit-compatible since it depends on np.unique and its output shape depends on the values in the array. This problem will be resolved as soon as np.unique is jit-compaitible #2760. 

The test check all one dimensional arrays and number dtypes which are not complex (as by #2760, unique does not work with complex dtypes). The test does not compile with jit since unique is not compatible with it.

2020-05-04 22:18 UTC, jekbradbury requested changes

2020-05-04 22:18 UTC, jekbradbury commented on jax/numpy/lax_numpy.py
> +    if ar1.ndim == 0:
This will fail if an input is a Python scalar rather than a NumPy/JAX scalar.

2020-05-04 22:18 UTC, jekbradbury commented on jax/numpy/lax_numpy.py
> +  aux.sort()
This relies on the in-place behavior of NumPy `sort`; you want to use something like `aux = sort(aux)` for JAX compatibility.

2020-05-21 15:16 UTC, joschkabraun commented
Okay, thank you for your feedback! I’m currently working on it and will finish it until the weekend!

2020-05-23 21:22 UTC, joschkabraun commented
The tests are running smooth on my local machine but I am getting errors here which seem to be outside of my code. Can you help me with them?

2020-05-24 14:37 UTC, jakevdp commented
As with #2941, you need to rebase on master, fix tests locally, and then force push to update this PR. Please let me know if you need help with that process.

2020-05-28 20:20 UTC, jakevdp commented
``rng_factory`` now requires ``self.rng()`` as the first argument - take a look at how other test routines use it.

2020-05-28 20:45 UTC, joschkabraun commented
Okay, thank you!

2020-05-28 21:27 UTC, joschkabraun commented
Running the tests here gives me the error "NotImplementedError: Numpy function <function setxor1d at 0x7fae7fd63ea0> not yet implemented". Do you know how that can happen?

2020-05-28 22:08 UTC, jakevdp commented
> Running the tests here gives me the error "NotImplementedError: Numpy function <function setxor1d at 0x7fae7fd63ea0> not yet implemented"

You'll need to add the function to the top-level imports here: https://github.com/google/jax/blob/e48a4e012bd253428e3bb0dd4ac5b163439a5270/jax/numpy/__init__.py#L20-L59

2020-05-29 12:44 UTC, joschkabraun commented
Okay, thank you!

2020-05-29 16:47 UTC, jakevdp commented
Looks like the remaining error is a dtype mismatch in x64 mode. I'd suggest passing ``check_dtypes=False`` in the test function.

2020-05-29 17:42 UTC, joschkabraun commented
Okay, thank you!

2020-05-29 17:43 UTC, jakevdp commented
Looks good - please also remove the two ``.orig`` files that were added along the way.

2020-05-29 19:49 UTC, joschkabraun commented
Okay, this has happened now!

2020-05-29 20:20 UTC, jakevdp requested changes

2020-05-29 20:20 UTC, jakevdp commented on jax/numpy/lax_numpy.py
> +    ar2 = asarray(ar2)
We should not call `asarray`; valid inputs will be properly handled by `concatenate`.

2020-05-29 20:20 UTC, jakevdp commented on jax/numpy/lax_numpy.py
> +      return aux
Use two-space indent to match the rest of the file.

2020-05-29 20:20 UTC, jakevdp commented on tests/lax_numpy_test.py
> +    jnp_fun = lambda ar1, ar2: jnp.setxor1d(ar1, ar2)
Since there's no complilation test, we can simplify to
```
np_fun = np.setxor1d
jnp_fun = jnp.setxor1d
```

2020-05-29 20:28 UTC, joschkabraun commented
Okay, incorporated changes!

2020-05-29 21:06 UTC, jakevdp commented
I just looked a bit closer at the numpy implementation: this seems to be essentially a line-for-line copy of the `setxor1d` code in numpy. That's fine, but for licensing purposes we'll need to move the implementation into ``jax/third_party/numpy`` before we can merge it.

2020-06-03 14:26 UTC, joschkabraun commented
Okay, that makes sense! Should I create a file `lax_numpy.py` similar to the structure in `jax/numpy` as there is only `linalg.py` in `jax/third_party/numpy`?

2020-06-03 17:27 UTC, jakevdp commented
Sure, you can create `jax/third_party/numpy/lax_numpy.py`, reflecting the structure of the main package.

2020-06-10 04:06 UTC, jakevdp approved these changes

2020-06-10 04:08 UTC, jakevdp commented
Looks great! The last thing we need is a rebase against master to fix the conflicts that have cropped up over the last few days. Please let me know if you need tips on how to do that.

2020-07-06 18:03 UTC, jakevdp commented
Hi – looks like something is strange with the rebase. If you need help getting your branch back in order, please let me know what commands you ran.

2020-07-14 18:35 UTC, jakevdp commented
Since there has been no action here for a while, I'm going to close this. Feel free to re-open if you'd like to re-visit this contribution! Thanks

2020-07-14 18:35 UTC, closed without merging