Experimental thick-restart Lancozs method for sparse eigenvalue problems
jax-ml/jax pull request #3114
Opened 2020-05-15 23:56 UTC by shoyer

I'm not sure if actually makes sense to merge this code. It probably needs some additional work/testing to make it more robust, but maybe `jax.experimental` would be a suitable incubator? Either way, hopefully it's a useful point of reference.

xref GH3112

2020-05-21 18:05 UTC, simbilod commented
Very nice. I am interested in automatic differentiation of sparse eigensolvers, but new to JAX -- did you already have something in mind about this? My only point of reference is this recent paper (https://arxiv.org/abs/2001.04121) where they reduce computing the adjoint to solving a low-rank linear problem. Maybe your new CG implementation could be used to that end?

2020-05-21 20:43 UTC, shoyer commented
Indeed, if the eigenvalues are unique, you can calculate eigenvalue/eigenvector derivatives in a straightforward fashion. That paper appears to have rediscovered a very old method for efficiently calculated eigenvector derivatives when not all eigenvectors are known, e.g., see this 1976 paper: https://arc.aiaa.org/doi/abs/10.2514/3.7211

There's actually a rather large literature on this problem from the field of computational mechanics. There are some other formulations that are supposed to be more numerically stable, e.g., so you don't need to solve a non-full rank system of linear equations: https://onlinelibrary.wiley.com/doi/abs/10.1002/cnm.895. I suspect the resulting linear equations are not necessarily positive, so we would more sophisticated iterative solvers such as (L)GMRES.

The challenge is how to define derivatives in the case of degenerate eigenvalues. In that case the eigenvalue problem necessarily isn't a well defined function, so calculating derivatives is quite challenging (maybe even impossible in reverse mode). But we probably don't need to worry this for a first-pass solution.

2020-05-28 22:34 UTC, jakevdp requested changes

2020-05-28 22:34 UTC, jakevdp commented on jax/experimental/lanczos.py
> +def _lanczos_restart(A, k, m, Q, alpha, beta):
A comment describing the meaning of each of these variables would be helpful.

2020-05-28 22:34 UTC, jakevdp commented on jax/experimental/lanczos.py
> +  """Find the `num_desired` smallest eigenvalues of the linear map A.
My experience with lanczos solvers is that they perform poorly for finding the smallest eigenvalues except in shift-invert mode, in which the smallest eigenvalues are transformed to the largest.

Have you tried modifying this to find the largest eigenvalues?

2020-05-28 22:34 UTC, jakevdp commented on tests/lanczos_test.py
> +    np.testing.assert_array_equal(actual, expected)
I think we have `self.assertArraysEqual` now

2020-05-28 22:34 UTC, jakevdp commented on tests/lanczos_test.py
> +    np.testing.assert_allclose(abs(v_actual), abs(self.v_expected), atol=1e-4)
`self.assertArraysAllclose`, here and below

2020-09-30 08:00 UTC, mganahl commented on jax/experimental/lanczos.py
> +    q_prev = Q[:, i]
Hi! I noticed that Krylov vectors are stored in column major format here. Would it make sense to switch to row-major?  Wondering if for large-dimensional vectors, zero-padding on TPUs could lead to an unnecessarily large memory footprint.

2023-11-03 22:00 UTC, jakevdp commented
This has become stale - I'm going to close. Feel free to re-open if you'd like to land this in `jax.scipy.sparse.linalg`

2023-11-03 22:00 UTC, closed without merging