Add note to docs describing how pytree arguments work.
jax-ml/jax pull request #3284
Opened 2020-06-01 23:49 UTC by skye

Addresses #3095. I'm not sure if we wanna link to this from API docstrings.

I'm also happy to drop this if we think this is better inlined directly into docstrings! (More briefly hopefully)

2020-06-01 23:50 UTC, skye commented on docs/pytree_arguments.rst
> +other container types as pytrees, see the "JAX pytrees" notebook under "Advanced
I cannot figure out how to get a :ref: working to link directly to this page, I'm open to any tips :)

2020-06-01 23:55 UTC, skye commented on docs/pytree_arguments.rst
> +other container types as pytrees, see the "JAX pytrees" notebook under "Advanced
I figured it out!

2020-06-02 01:31 UTC, jekbradbury commented on docs/pytree_arguments.rst
> +This happens to the default ``in_axes`` value!
```suggestion
This happens to be the default ``in_axes`` value!
```

2020-06-02 01:32 UTC, jekbradbury commented on docs/pytree_arguments.rst
> +``jit``'s ``static_argnums``.
I don't think it applies to `static_argnums`, although it could if that kwarg had a different API?

2020-06-02 06:31 UTC, gnecula requested changes
Thanks for writing this. I think that this should be merged with "JAX pytrees". Perhaps it makes sense to copy here the contents of the JAX pytrees notebook. (I think that we should reduce the use of notebooks as documentation, keeping it for the cases where people really would clone it and play with it)

2020-06-02 06:31 UTC, gnecula commented on docs/pytree_arguments.rst
> +array. In other words, a pytree is just **a possibly-nested standard Python
I would replace "standard" with "standard or user-registered"

2020-06-02 06:31 UTC, gnecula commented on docs/pytree_arguments.rst
> +leaf values are "matched up" with the corresponding input and output leaf
Technically it is "input and output leaf or subtree", but maybe that it too much at this point.

2020-06-02 06:31 UTC, gnecula commented on docs/pytree_arguments.rst
> +Note that the input arguments to a function are considered a tuple. We can use
This reads strange: "if we pass ... Note". I would just say "if we pass ... we can use ... . Note ..."

2020-06-02 06:31 UTC, gnecula commented on docs/pytree_arguments.rst
> +
I would say explicitly that this is equivalent to `(None, {"k1": 0, "k2": 0})`.

2020-06-02 19:12 UTC, skye reviewed
I combined with the pytrees notebook, under the heading "Developer information". It's mostly copy/paste but I reworded the beginning a little to not repeat information and changed the headings. PTAL.

2020-06-03 12:51 UTC, gnecula approved these changes

2020-06-03 16:46 UTC, merged