WIP: hfft and ihfft implementation
jax-ml/jax pull request #3664
Opened 2020-07-05 20:50 UTC by aldragan0

Please see [#1877 ](https://github.com/google/jax/issues/1877) for reference.

2020-07-05 21:00 UTC, aldragan0 commented
Some tests for these functions are failing due either the tests using unsupported formats for lax.conj() like np.bool or in the "testFftErrors" because there are no checks made for the axis.

I would really appreciate some guidance or feedback for this.

2020-07-06 14:48 UTC, hawkinsp commented
The error I see in the CI is:
```
tests/fft_test.py:201: in <lambda>
    lambda: func(rng([2, 3], dtype=np.float64), axis=[1, 1])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    @_wraps(np.fft.hfft)
    def hfft(a, n=None, axis=-1, norm=None):
      conj_a = lax.conj(a)
>     nn = (a.shape[axis] - 1) * 2 if n is None else n
E     TypeError: tuple indices must be integers or slices, not list
```
which is an error in your PR: it appears the test is passing `axis=[1, 1]`, but the implementation of `hfft` does not handle that case.

Note the test case is explicitly testing handling of illegal axis specifications, so the correct thing for your code to do here is to raise an exception if it sees an axis that isn't an integer (which is all `hfft` seems to accept: https://numpy.org/doc/stable/reference/generated/numpy.fft.hfft.html#numpy.fft.hfft ), and modify or extend the tests to expect that error from `hfft`.

2020-07-06 16:28 UTC, aldragan0 commented
Should I also modify the tests to accept the TypeError thrown by the lax.conj in case invalid input type is given?
[fft_tests.log](https://github.com/google/jax/files/4880147/tests.log)

2020-07-06 16:54 UTC, hawkinsp commented
It appears that `numpy.fft.hfft` accepts integer inputs (and casts them to an inexact type). So ideally your implementation of `jax.numpy.fft.hfft` should also; it should not error. There are `promote_to_...` helper functions in `lax_fft.py` that you could use here.

2020-07-06 17:01 UTC, hawkinsp commented
You could probably also call `jnp.conj`, which is more liberal in what it accepts than `lax.conj`.

2020-07-06 17:13 UTC, aldragan0 commented
Thank you, fixed the failing tests now.

2020-07-07 23:38 UTC, skye requested changes

2020-07-07 23:38 UTC, skye commented on jax/numpy/fft.py
> +  return _fft_core_1d('irfft', xla_client.FftType.IRFFT, conj_a, s=n, axis=axis,
```suggestion
  return _fft_core_1d('hfft', xla_client.FftType.IRFFT, conj_a, s=n, axis=axis,
```

2020-07-07 23:38 UTC, skye commented on jax/numpy/fft.py
> +  output = _fft_core_1d('rfft', xla_client.FftType.RFFT, a, s=n, axis=axis,
```suggestion
  output = _fft_core_1d('ihfft', xla_client.FftType.RFFT, a, s=n, axis=axis,
```

2020-07-09 17:06 UTC, skye approved these changes

2020-07-09 17:06 UTC, skye commented
I'll merge assuming the presubmits pass, thanks!

2020-07-10 17:35 UTC, merged