Add array_split (#70)
jax-ml/jax pull request #4197
Opened 2020-09-02 21:11 UTC by ajcr

This implements `array_split`.

As I was finishing this change, I noticed an [existing open draft PR for `array_split`](https://github.com/google/jax/pull/3639) (my fault for missing it when I checked first time round!).

Because that PR appears to have been inactive for some time and my code is quite different, I've opened a new PR here. However, if the other PR should be given priority, I'm happy to close this as a duplicate and for my proposed changes to be recycled if useful.

2020-09-02 21:32 UTC, jakevdp commented on jax/numpy/lax_numpy.py
> +    indices_or_sections = [core.concrete_or_error(int, i_s, "in jax.numpy.{} argument 1".format(op))
You could use an f-string here: `f"in jax.numpy.{op} argument 1"`

2020-09-02 21:42 UTC, jakevdp requested changes
Looks great, thanks for your work on this! Just a few minor comments.

The other PR has been inactive long enough that I think it's fine to move forward with this one.

2020-09-02 21:42 UTC, jakevdp commented on jax/numpy/lax_numpy.py
> +def _split(ary, indices_or_sections, axis=0, op="split"):
Minor: I'd make `op` the first argument with no default value.

2020-09-02 21:42 UTC, jakevdp commented on tests/lax_numpy_test.py
> +       "dtype": dtype, "rng_factory": jtu.rand_default}
We no longer pass rng_factory as a testcase argument. You can use `jtu.rand_default` directly.

2020-09-02 21:55 UTC, ajcr commented
Thanks for the review, @jakevdp - I've made the changes you've suggested, let me know if there's anything else I can do.

2020-09-02 22:08 UTC, jakevdp commented
Looks great! One last thing: to make this appear on the documentation website, the function needs to be added to the autosummary list here: https://github.com/google/jax/blob/master/docs/jax.numpy.rst

2020-09-02 22:17 UTC, ajcr commented
Ah I see - no problem, it should be there now.

2020-09-02 22:19 UTC, jakevdp approved these changes

2020-09-02 22:19 UTC, jakevdp commented
Looks great! Once tests pass we can get this merged.

2020-09-02 23:13 UTC, merged

2020-09-03 04:50 UTC, AdrienCorenflos commented
Ah yeah I had completely forgotten about the fact I had opened that PR! My bad.