Add jax.numpy.polyint
jax-ml/jax pull request #4539
Opened 2020-10-11 09:23 UTC by schmrlng

Though not mentioned in the numpy [documentation](https://numpy.org/doc/stable/reference/generated/numpy.polyint.html), this implementation matches `np.polyint` in the cases `m > 1 and len(k) == 1` as well as `len(k) > m`.

I've also added some `np.` (i.e., base `numpy`) qualifiers in the `polyder` implementation as my impression is that this improves constant-folding for `jax.make_jaxpr` and `jax.jit`.

2020-10-12 16:29 UTC, jakevdp requested changes
Looks great! Thanks for the contribution. A few minor comments, and then we can get this in.

Also, if you're able to squash the additional changes so that this PR is a single commit, that would be much appreciated.

2020-10-12 16:29 UTC, jakevdp commented on jax/numpy/lax_numpy.py
>  def polyder(p, m=1):
If we're requiring `m` to be concrete (as implied by the change from `arange` to `np.arange` below), then we should call
```python
m = core.concrete_or_error(int, m, "The error arose in jnp.polyder argument `m`")
```
Same in `polyint` below.

2020-10-12 16:29 UTC, jakevdp commented on jax/numpy/lax_numpy.py
> +  p = asarray(p)
We're moving toward requiring inputs to be arrays to start with (though proceeding carefully for existing functions for backward compatibility). For a new function like this, we should call `_check_arraylike('polyint', p)` before `p = asarray(p)`.

Similar for `k` when it is not `None`.

2020-10-12 16:29 UTC, jakevdp commented on tests/lax_numpy_test.py
> +    args_maker = lambda: [rng(a_shape, dtype), None if k_shape is None else rng(k_shape, dtype)]
I can never remember the precedence order of commas and ternary operators. For readability, could you add some parentheses to make this clearer? e.g.
```
lambda: [rng(a_shape, dtype), (None if k_shape is None else rng(k_shape, dtype))]
```

2020-10-17 16:43 UTC, hawkinsp commented
Just as an FYI: we moved some of these files into `jax/_src/numpy`, so you'll need to rebase your PR on top of head.

2021-02-27 01:16 UTC, jakevdp commented
`polyint` was added in #5731

2021-02-27 01:16 UTC, closed without merging