Add fast path for jnp.repeat when repeats is a scalar constant.
jax-ml/jax pull request #4639
Opened 2020-10-19 12:30 UTC by petebu

The default code-path generates a complicated soup of ops for this very simple case what can be implemented using reshapes and broadcasts only.

2020-10-19 13:06 UTC, hawkinsp requested changes

2020-10-19 13:06 UTC, hawkinsp commented on jax/_src/numpy/lax_numpy.py
> +      a = reshape(a, np.insert(input_shape, axis, 1))
`lax.expand_dims`

?

2020-10-19 14:25 UTC, mattjj approved these changes
Thanks for this improvement!

+1 to hawkinsp@'s comment.

Consider this optional, but since all untested code is (eventually) broken, I wonder how we might add a test for this. Maybe we could just call `make_jaxpr` and check the number of eqns is only ~3?

2020-10-19 14:25 UTC, mattjj commented on jax/_src/numpy/lax_numpy.py
> +      a = reshape(a, np.insert(input_shape, axis, 1))
+1

2020-10-23 12:16 UTC, petebu commented on jax/_src/numpy/lax_numpy.py
> +      a = reshape(a, np.insert(input_shape, axis, 1))
That's better. Thanks!

2020-10-23 12:18 UTC, petebu commented
> Thanks for this improvement!
> 
> +1 to hawkinsp@'s comment.
> 
> Consider this optional, but since all untested code is (eventually) broken, I wonder how we might add a test for this. Maybe we could just call `make_jaxpr` and check the number of eqns is only ~3?

Good idea. In fact, the original code was wrong but wasn't being called so the tests passed anyway. I've just committed a fix and added a test for the number of eqns.

2020-10-23 12:20 UTC, petebu commented
Before this PR, `jnp.repeat(jnp.array([1,2,3,4]), repeats=2)` generated 21 Jaxpr eqns. Now it's down to 6.

2020-10-24 00:39 UTC, hawkinsp approved these changes

2020-10-24 02:22 UTC, mattjj approved these changes
Extra LGTM for an extra good PR.

2020-12-07 17:29 UTC, merged