Make xmapped functions with no axis resources callable more than once
jax-ml/jax pull request #5362
Opened 2021-01-11 10:45 UTC by apaszke

When no XLA lowering was involved (i.e. when using a purely vectorized
schedule), we used to return `f.call_wrapped` as the xmapped function.
This obviously didn't end well when someone tried to call it multiple
times, which this patch should fix.

2021-01-11 10:45 UTC, apaszke commented
cc @levskaya

2021-01-11 15:59 UTC, mattjj approved these changes
LGTM! (Not sure what's up with the CI failure; I saw it locally too, and assumed jaxlib needed an update...)

2021-01-12 07:26 UTC, levskaya reviewed
Thanks for the fix, Adam!

2021-01-15 07:02 UTC, levskaya commented on jax/experimental/maps.py
> +    return core.jaxpr_as_fun(core.ClosedJaxpr(jaxpr, consts))
shouldn't these be 'final_jaxpr' and 'final_consts' from right above?

2021-01-15 08:21 UTC, levskaya requested changes

2021-01-15 08:21 UTC, levskaya commented on tests/xmap_test.py
> +                      axis_resources=dict(axis_resources))
If the test is using axis_resources / mesh then it's not actually going to exercise the problematic branch, is it?

2021-01-15 08:21 UTC, levskaya commented on jax/experimental/maps.py
> +    final_jaxpr, _, final_consts = pe.trace_to_jaxpr_final(f, mapped_in_avals)
Correct me if I'm wrong - shouldn't this be using in_avals?  Some tests suggest this is the case.
```python
final_jaxpr, _, final_consts = pe.trace_to_jaxpr_final(f, in_avals)
return core.jaxpr_as_fun(core.ClosedJaxpr(final_jaxpr, final_consts))
```

2021-01-15 11:44 UTC, merged

2021-01-18 20:29 UTC, levskaya commented on tests/xmap_test.py
> +                      axis_resources=dict(axis_resources))
Adam - sorry I just misread the conditions the first time!

2021-01-18 20:31 UTC, levskaya commented on jax/experimental/maps.py
> +    final_jaxpr, _, final_consts = pe.trace_to_jaxpr_final(f, mapped_in_avals)
@apaszke - sorry - I'm not sure the correct fix went in with this merge?