Security an Compatibility Fix
jax-ml/jax pull request #6949
Opened 2021-06-11 08:08 UTC by krvaibhaw

* Update mypy version to 0.902
* Update numpy minimum version to 1.16
* Update jax2tf README.md

2021-06-11 08:11 UTC, krvaibhaw commented
@googlebot I signed it!

2021-06-11 16:47 UTC, jakevdp commented
Thanks! I think some of these changes may conflict with https://github.com/google/jax/pull/6941, which was just merged this morning. Can you rebase your PR on the current master branch?

2021-06-11 17:44 UTC, hawkinsp requested changes
I'd split this PR up into two, and give each a better title (e.g., I'm not sure how this is related to security, for example...)

2021-06-11 17:44 UTC, hawkinsp commented on setup.py
> +        'numpy >=1.17',
Revert this change.

2021-06-11 17:44 UTC, hawkinsp commented on build/test-requirements.txt
> +mypy==0.902
Please do not mix different kinds of changes in the same PR. Bumping the mypy version and improving the docs are both fine things to do, but please do them in separate PRs that try to do one thing only.

2021-06-11 23:00 UTC, hawkinsp commented on build/test-requirements.txt
> +mypy==0.902
This still need to be addressed. I would just revert the mypy change from this PR and send it as a separate PR.

Please also squash your commits and fix the title and commit comments to reflect that this is a doc-only change.

2021-06-11 23:04 UTC, hawkinsp requested changes

2021-06-11 23:04 UTC, hawkinsp commented on jax/experimental/jax2tf/README.md
> +  * addition, subtraction, multiplication are supported without restrictions and
Revert this change. I think the comma makes it read more clearly.

2021-06-11 23:04 UTC, hawkinsp commented on jax/experimental/jax2tf/README.md
> +  * the division is a special case. It is also overloaded, but it is only partially
Revert this change. It reads better without the "the".

2021-06-11 23:04 UTC, hawkinsp commented on jax/experimental/jax2tf/README.md
> +     cases but not always. Also, `tf.gather` has different semantics than `lax.gather`
It's not clear to me this change is a correct usage of "semantics". Revert it.

2021-06-11 23:04 UTC, hawkinsp commented on jax/experimental/jax2tf/README.md
> +In JAX, there is no primitive for batch normalization, and instead, the
Revert this change. It reads better without the additional comma.

2021-06-11 23:04 UTC, hawkinsp commented on jax/experimental/jax2tf/README.md
> +then either the TensorFlow native or JAX native batch normalization.
Revert this change. "differently than" is the correct spelling.

2021-06-23 13:13 UTC, hawkinsp requested changes
Please squash your commits as well.

2021-06-23 13:13 UTC, hawkinsp commented on build/test-requirements.txt
> +.[minimum-jaxlib]
There's still an unnecessary change to this file.

2023-11-20 15:52 UTC, closed without merging