Turn transposed_fun into a PyTree
jax-ml/jax pull request #7191
Opened 2021-07-05 09:37 UTC by inailuig

Follow-up to https://github.com/google/jax/pull/7101, as suggested in https://github.com/google/jax/discussions/7053#discussioncomment-917964. 

Allows using the function returned by jax.linear_transpose with jit. 

Example:

```python
import jax
import jax.numpy as jnp
from functools import partial

A = jnp.array([[1.,2.],[3.,4.]])
x = jnp.array([5., 6.])
y = jnp.array([7., 8.])

def f(x):
    return A@x

@partial(jax.jit, static_argnums=0)
def transpose(f, x):
    return jax.linear_transpose(f, x)

ft = transpose(f, x)

assert jnp.allclose(ft(y), A.T@y)
assert jnp.allclose(jax.jit(ft)(y), A.T@y)
```

2021-07-13 08:34 UTC, PhilipVinc commented
@mattjj gentle bump.
Would love to have this in the next jax release

2021-07-19 14:39 UTC, PhilipVinc commented
@gnecula sorry to bother, but we'd love this patch merged before the next jax release... I think @mattjj might be on holiday?

2021-07-19 14:48 UTC, gnecula commented
I suggest adding a test that demonstrates this feature

2021-07-19 18:58 UTC, froystig requested changes
The change looks good to me, though I agree a test would be good. How about converting the example from the PR description into a test in `tests/api_test.py`, within the `APITest` class?

2021-07-21 14:03 UTC, inailuig commented
I added a test for this PR, and for completeness also the same for linearize (since https://github.com/google/jax/pull/7101) and vjp.

2021-07-21 18:09 UTC, froystig approved these changes
Very nice! Thank you.

2021-07-22 16:40 UTC, merged