Jittable eigh
jax-ml/jax pull request #7477
Opened 2021-08-03 21:24 UTC by adam-lewis-gcorp

@hawkinsp @tlu7 @rmlarson

This commit evades the varying blocksize issue associated with QDWH-SVD by using a different polynomial iteration that computes a rank-k orthogonal projector for given k directly. The specific algorithm is described here: https://core.ac.uk/download/pdf/79508571.pdf.

I'd been trying to avoid this because the performance and error behaviour, while still not awful, tends not to be quite so good as obtained by QDWH. But the solutions I came up with turned out to be generally even worse.

2021-08-03 21:52 UTC, hawkinsp commented on jax/_src/scipy/eigh.py
> +  return jax.ops.index_update(X, jnp.diag_indices(X.shape[0]), vals)
JAX style thing: I'd always prefer `X.at[index].update(y)` over `index_update` these days. They are synonyms but I think the terser syntax is more readable.

2021-08-30 17:09 UTC, rmlarsen requested changes

2021-08-30 17:09 UTC, rmlarsen commented on tests/lax_scipy_test.py
> +    #guess = jax._src.scipy.eigh._canonically_purify_initial_guess(H, linear_size // 2)
delete?

2021-08-30 17:09 UTC, rmlarsen commented on tests/lax_scipy_test.py
> +    for dtype in [jnp.float32, ]))
revert?

2021-08-30 17:09 UTC, rmlarsen commented on tests/lax_scipy_test.py
>    def test_spectral_dac_svd(self, linear_size, seed, dtype):
let's use "bisection" instead of "dac" (which is hardcoded to translate to "digital to analog converter" in my brain ;-) )

2021-08-30 17:09 UTC, rmlarsen commented on tests/lax_scipy_test.py
> +linear_sizes = [8,] #128, 256]
revert? We should test for larger sizes.

2021-08-30 17:09 UTC, rmlarsen commented on jax/_src/scipy/eigh.py
> +  evals = evals[sort_idxs]
out of curiosity: Does JAX have a fast O(n) in-place permute implementation?

2021-08-30 17:09 UTC, rmlarsen commented on jax/_src/scipy/eigh.py
> +  beta = theta / (lambda_max - mu)
We should probably guard against division by zero here. This would blow up for H=eye(n), I think.

2023-11-03 15:25 UTC, closed without merging

2023-11-03 15:25 UTC, hawkinsp commented
Closing. We've had a `jit`-table `eigh` for some time by using a bucketing and padding strategy.