add support for scipy.special.{expn,expi,exp1}
jax-ml/jax pull request #7692
Opened 2021-08-21 20:09 UTC by terhorst

This PR adds support for some exponential integral functions. The code is based off of Cephes, so there shouldn't be any licensing issues. I believe the underlying code is all correct, as it validates against the scipy version as well as check_grad. However, I am not able to get it to pass the jax test suite--I get a cryptic error about recompilation that I have not been able to solve. I think it may be related to use of `jnp.piecewise`, but I cannot see why. I'm submitting this PR in hopes that someone else may understand what's going on.

2021-08-22 18:55 UTC, terhorst commented
jitting solves the issue described above for exp1 and expn. For expi, now I get a leaked tracer.

2021-08-23 16:30 UTC, jakevdp requested changes
Looks great! Thanks for digging-in on this. A couple minor changes below; also I think we can get #7693 fixed today to allow full testing here.

2021-08-23 16:30 UTC, jakevdp commented on jax/_src/scipy/special.py
> +    A = [
Please add a comment that indicates the source of the algorithm used here

2021-08-23 16:30 UTC, jakevdp commented on jax/_src/scipy/special.py
> +    # 0 < x <= 2
Please use two spaces for indentation

2021-08-23 16:30 UTC, jakevdp commented on jax/_src/scipy/special.py
> +    # w, f, x = id_print((w, f, x), what="eval_expint")
Remove?

2021-08-23 16:30 UTC, jakevdp commented on jax/_src/scipy/special.py
> +        from jax.scipy.special import gammaln
I think this import can be removed, because gammaln is defined above in this file

2021-08-23 16:30 UTC, jakevdp commented on jax/_src/scipy/special.py
> +    return d["z"] ** r * psi / gamma(t) - d["ans"]
use `jnp.exp(gammaln(t))` inline here?

2021-08-23 17:14 UTC, terhorst commented
All done. I removed the jits in anticipation of resolving #7693.

2021-08-23 18:57 UTC, jakevdp commented
I'm not sure how soon #7693 will be resolved (in my judgment, the fix seems more complicated than is warranted for the issue) so if you have a way to make these tests pass without it, we should probably go with that.

2021-08-23 20:09 UTC, terhorst commented
Okay, I added them back.

2021-08-23 20:10 UTC, jakevdp approved these changes

2021-08-24 18:10 UTC, jakevdp commented
Hi - just FYI, the delay in merging this is due to the fact that the exp1 tests fail on GPU with an error that I'm having difficulty debugging.

2021-08-24 18:16 UTC, jakevdp commented
My working theory is that might somehow be due to the inefficiency of the implementation (the GPU abort looks like it may come from resources being exhausted somehow) – I wonder if rather than using `piecewise` over multiple functions containing different constants, it might be more efficient to put all the constants in a 2D array and use `jnp.where` to select the applicable row?

2021-08-24 18:27 UTC, jakevdp commented
To be more concrete, this is the failure we're seeing:
```
[ RUN      ] LaxBackedScipyTests.testScipySpecialFunExp1_float64[]
W0824 09:08:23.276341    5286 symbolize_elf.inc:1312] RAW: /build/cas/3fe/3fec575d73fe9a7bdb835176c490dd0b8690e3f8aaeef028ac72e1df44121122_02005d5b2df8: too many executable LOAD segments
F0824 09:08:23.275103    5286 nvptx_compiler.cc:480] ptxas returned an error during compilation of ptx to sass: 'INTERNAL: ptxas exited with non-zero error code 11, output: '  If the error message indicates that a file could not be written, please verify that sufficient filesystem space is provided.
```

2021-08-24 18:28 UTC, terhorst commented
Thanks for the update. The tests pass on my GPU and `jaxlib[cuda11]`--what is the error you're getting. Re: `jnp.where`, that should be possible by zero-padding all the A and B arrays (from the front) to have equal length.

2021-08-24 18:29 UTC, terhorst commented
Oh thanks, just saw your message. Yeah I would have no idea how to debug that :-) Let me try your suggestion, I'll push in a sec.

2021-08-24 18:34 UTC, terhorst commented
Actually if it's failing on `exp1` then it's unrelated to the use of `piecewise` to select the correct rational function approximation. Those only get invoked for `expi`. `expi` does end up calling `expn` to handle negative arguments, but not the other way around (confusing I know). 

Can you check if the same failure occurs for `exp1` specifically? `exp1`/`expn` also employ `piecewise`, but in a way that's harder to eliminate.

2021-08-24 18:50 UTC, jakevdp commented
It looks like all three functions cause a similar error, but only for float64. So I think for this PR, maybe the best option is in the tests to change `float_dtypes` to `[np.float32]` and leave a TODO to run tests for float64 as well.

2021-08-24 18:52 UTC, jakevdp commented
Given that float64 is skipped by default, you may be able to reproduce this using
```
$ JAX_ENABLE_X64=1 pytest -n auto tests/lax_scipy_test.py -k SpecialFunExp
```

2021-08-24 19:09 UTC, terhorst commented
Even enabling x64, everything passes locally for me, so it's going to be hard to debug further. Restricting the tests to float32 seems like a fine option.

2021-08-24 20:25 UTC, jakevdp commented
Would you be willing to make those test changes, and then also squash all the changes into a single commit? Thanks!

2021-08-24 22:30 UTC, merged

2021-08-24 23:56 UTC, jakevdp commented
Looks like it's in! Thanks for the work on this!