XLA translation rule for linear_call
jax-ml/jax pull request #7833
Opened 2021-09-07 08:36 UTC by inailuig

This adds the missing XLA translation rule for linear_call so that it can be jitted.
I'm not super familiar with this part of the jax source code, but I replicated what was done for `linear_solve_p`.

Example:
```python

import jax
from jax.custom_derivatives import linear_call 
from functools import partial

def f(r, x):
   return x / r

def t(r, t):
   return t / r

def div_add(x, denom):
   return x + linear_call(f, t, denom, x)

def transpose(f, x_example):
   def transposed(y):
     x, = jax.linear_transpose(f, x_example)(y)
     return x
   return transposed

print(jax.jit(div_add)(9., 3.))
print(jax.jit(transpose(partial(div_add, denom=3.), 1.))(18.))
```
```
12.0
24.0
```
which before was throwing `NotImplementedError: XLA translation rule for primitive 'linear_call' not found`)

This should allow to workaround https://github.com/google/jax/issues/6619, as suggested in the last bullet point in
https://github.com/google/jax/issues/6619#issuecomment-841504388.

2021-09-10 09:51 UTC, PhilipVinc commented
By the way, @froystig , we are also wondering if `linear_call` is part of the public jax API and if it is safe for us to use it.

2021-09-11 00:02 UTC, froystig commented
I would anticipate changes as we build out custom transposition more completely (it's on my queue). That said, while interface details may change, the ability to define custom transposition behavior should remain, and will ideally only improve in various ways.

2021-09-11 01:18 UTC, froystig requested changes
Thanks! How about a test? Maybe define a function `f` that uses `linear_call` and then compare `jit(f)(x)` to `f(x)`? A good place would be `api_test.CustomTransposeTest`.

2021-09-14 11:08 UTC, inailuig commented
@froystig I added a test.

2021-09-14 18:37 UTC, froystig approved these changes
thanks!

2021-09-15 21:23 UTC, merged