Allow `random.choice` and `random.permutation` on multidimensional arrays
jax-ml/jax pull request #8161
Opened 2021-10-11 18:04 UTC by juliuskunze

Fixes https://github.com/google/jax/issues/8158.

2021-10-11 22:33 UTC, jakevdp requested changes
Looks great!

One minor comment (feel free to ignore). Also, please add an entry to the changelog, and squash all changes into a single commit. Thanks!

2021-10-11 23:53 UTC, jakevdp approved these changes

2021-10-12 00:37 UTC, juliuskunze commented
@jakevdp Done. Let me know if I can help to fix the Google internal error.

2021-10-13 16:31 UTC, jakevdp commented
Thanks for your work on this!

2021-10-13 16:31 UTC, merged