support null shape in jax.random.poisson
jax-ml/jax pull request #8390
Opened 2021-10-28 19:24 UTC by rakki-18

Fixes #7861 

## Issue
```python
jax.random.poisson(key,lam)
```
was giving errors, because default `shape` was not being broadcasted to `lam`

## Changes introduced
- If `shape` argument is not given to `jax.random.poisson`,
it takes the shape of `lam.shape`
- Added tests to cover the case of default shape
```Python
jax.random.poisson(key,lam)
```

2021-11-30 20:37 UTC, jakevdp requested changes
Hi - sorry this fell off my radar. Thanks for the contribution! A few small changes and then we can get this merged.

2021-11-30 20:37 UTC, jakevdp commented on jax/_src/random.py
> +            shape: Sequence[int] = None,
This is now `Optional[Sequence[int]]`

2021-11-30 20:37 UTC, jakevdp commented on jax/_src/random.py
>      lam = jnp.broadcast_to(lam, shape)
Not part of your change, but here it's better to call `lam = jnp.broadcast_to(lam, shape)` in all cases.

2021-11-30 20:37 UTC, jakevdp commented on tests/random_test.py
> +    self._CheckChiSquared(samples,scipy.stats.poisson(2.0).pmf)
minor: please add a space after commas, and add a space before and after operators like `*`

2021-12-27 06:09 UTC, rakki-18 commented
@jakevdp Really sorry for the delay. I have made the changes requested. Could you please review it now?

2021-12-28 17:36 UTC, jakevdp approved these changes
Looks good, thanks!

2021-12-28 17:58 UTC, jakevdp commented
Looks like there are a couple flake8 issues – once these are addressed we can get this merged. Thanks!

2021-12-28 19:25 UTC, rakki-18 commented
> Looks like there are a couple flake8 issues – once these are addressed we can get this merged. Thanks!

@jakevdp I have fixed them now

2021-12-28 20:07 UTC, jakevdp commented
Thanks - can you squash all the changes into a single commit please?

2021-12-29 10:03 UTC, rakki-18 commented
> Thanks - can you squash all the changes into a single commit please?

@jakevdp I have squashed changes into a single commit now.

2021-12-29 12:38 UTC, jakevdp approved these changes

2021-12-30 09:31 UTC, merged