Implement jax2tf scatter_* ops with no XLA
jax-ml/jax pull request #9289
Opened 2022-01-22 09:49 UTC by oliverdutton

Linking to #9269

This is a work in progress, it seems to work for the simplest examples. Will update with tests, etc.

2022-01-22 10:35 UTC, oliverdutton commented
I'm doing this to convert some JAX code to ONNX. I find that my current fix using
```python
tensor_scatter_nd_add
tensor_scatter_nd_max
tensor_scatter_nd_min
```

don't get converted by tf2onnx, while `tensor_scatter_nd_update` works fine and my devolved implementation of `scatter_mul` in JAX converts correctly. So I'm going to reimplement `add,max,min` similarly to how `mul` is currently

2022-01-22 10:47 UTC, oliverdutton commented
Reimplementation looks prettier in the onnx representation

Pic below is scatter_add.
![image](https://user-images.githubusercontent.com/44170519/150635380-fb638422-50a0-43d2-8ef9-8bbb15821fed.png)

2022-01-25 13:22 UTC, gnecula requested changes
Please see the suggestions about testing in #9269

2022-01-25 13:55 UTC, oliverdutton commented on jax/experimental/jax2tf/impl_no_xla.py
> +for (xla_op, segment_op, update_op) in [
Probably best unrolled.

2022-01-31 14:22 UTC, oliverdutton commented
I have found other routes for the task than no_xla, closing task. Thank you for your suggestions and comments.

2022-01-31 14:22 UTC, closed without merging

2022-03-31 09:46 UTC, marcvanzee commented
@oliverdutton for reference, what other route did you find?

2022-03-31 10:45 UTC, oliverdutton commented
Implementing the XLA op on the backend directly.  This meant I didn't need the format changing to ONNX which is what pushed me to look at no XLA scatter.