Clarified tree_flatten is_leaf docstring.
jax-ml/jax pull request #9569
Opened 2022-02-15 08:22 UTC by GJBoth

This tiny PR clarifies the `tree_flatten` docstring for the `is_leaf` option as per #9520. The is_leaf option of the tree_flatten function is currently described as,

> an optionally specified function that will be called at each flattening step. It should return a boolean, which indicates whether the flattening should traverse the current object, or if it should be stopped immediately, with the whole subtree being treated as a leaf.

This seems to imply true should be returned if the object needs to be traversed, and false if it is a leaf. This PR changes it to something more explicit:

>   an optionally specified function that will be called at each flattening step. It should return a boolean, with true stopping the traversal and the whole subtree being treated as a leaf, and false indicating the flattening should traverse the current object.

2022-02-18 15:12 UTC, GJBoth commented
Submitted the PR under my own name and email and squashes everything into a single commit! Not sure why read the docs is failing though?

2022-02-18 17:40 UTC, jakevdp requested changes

2022-02-21 07:51 UTC, GJBoth commented on jax/_src/tree_util.py
> +    indicating the flattening should traverse the current object.
Done!

2022-02-24 19:13 UTC, jakevdp approved these changes
Thanks!

2022-04-14 23:09 UTC, merged